services:
  leaguebot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: long-horns
    container_name: long-horns
    volumes:
      - .:/service

volumes:
  sqlitedb:
